name: "hero-action"
branding:
  icon: "align-justify"
  color: "white"
description: "All-in-one action to develop and maintain GitHub Actions"
inputs:
  # ...

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --src_file_path
    - ${{ inputs.src-file-path }}
    - --dst_file_path
    - ${{ inputs.dst-file-path }}
    - --start_value
    - ${{ inputs.start-value }}
    - --end_value
    - ${{ inputs.end-value }}
    - --git_user_name
    - ${{ inputs.git-user-name }}
    - --git_user_email
    - ${{ inputs.git-user-email }}
    - --git_commit_msg
    - ${{ inputs.git-commit-msg }}
    - --git_skip_commit
    - ${{ inputs.git-skip-commit }}
    - --git_skip_push
    - ${{ inputs.git-skip-push }}
    - --create_backup
    - ${{ inputs.create-backup }}
